### ISSUE TITLE
make releases?

### ISSUE THREAD

**Issue by rfht** [FNA-XNA/Theorafile#2]
Any chance that this one could be bundled in a release? Ideally with a tarball of the source code uploaded (besides the auto-generated stuff) - with it being in our OpenBSD ports tree, at times github changes its tools and stuff and the size and hash of what's pulled in a commit (or autogenerated release tarballs) changes, breaking the port...

Thanks!

**Comment by flibitijibibo** [comment]
Turns out I didn't have my own repo watched... anyway:

Technically it has been uploaded/released, but as part of the FNA releases. The source is in `lib/Theorafile/`. That's sort of my cop-out answer, as I don't know if this matters to anyone other than FNA hackers so adding another package to my pile o' packages would be kind of annoying. (Plus if I tried to submit this to a distro as a real thing I'm sure they'd just laugh at it...)

Non-GitHub archives can be found at http://fna.flibitijibibo.com/archive/

**Comment by rfht** [comment]
Thanks, it might be the best way for the port then to work with the folder in the FNA releases. I didn't think of that before, but I think this approach should be viable. Main challenge might be to track when an FNA release contains an updated theorafile and then bump the port and library version accordingly.

I think I'll take the FNA releases from github then because of https :)

I'm closing this issue because this will likely resolve the issue.
